### ISSUE TITLE
Flag Icons

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#21]
Flag icons for the language doesn't work?

**Comment by MortenHofft** [comment]
I need a bit more context. What are you trying to do and what have you tried? Do you have a commit or an example?

**Comment by MortenHofft** [comment]
https://hp-theme.gbif-staging.org/translations
I've added a flag emoji for Fijian - i just copied it from here https://emojipedia.org/flags/

it shows as in below screenshot

<img width="145" alt="Screenshot 2021-09-10 at 09 18 51" src="https://user-images.githubusercontent.com/6759267/132815457-85bd1e5e-2383-4ca7-8ed9-469b91084d08.png">

Is that what you were trying to do? I think it is also possible to provide your own images if you so prefer (instead of an emoji)

Be aware that the problem with flags is that some people find them a bit insulting (what flag is english and french for example). So unless you really are targeting countries, then it might be better to avoid them.

**Comment by aserawayneasera** [comment]
Thanks Morten. Sorry for the lack of information. I tried it maybe 3-4 months ago and didn't work by adding GB for English in the icon field under the language file. I assumed it still wasn't working. I'll try this. Thanks again

**Comment by aserawayneasera** [comment]
![image](https://user-images.githubusercontent.com/27858318/133148757-02859fda-9b71-47f7-b8d7-6b9b239097c1.png)

it does show on my phone when I view it but on testing it is displaying the letters shown above.

**Comment by MattBlissett** [comment]
I see this on Firefox on Linux: 
![image](https://user-images.githubusercontent.com/583320/133221191-3f49b3a0-8011-46cb-bbfe-12e012ef7565.png)

Could it be missing fonts?

**Comment by MortenHofft** [comment]
I wasn't aware that emojis could be an issue. I presume your device do not have the corresponding icons. I've changed it to rely only on images. I've updated Samoan with an example. I took the flag icon from https://flagicons.lipis.dev/

No one else is using this, so I've just changed the way it renders.

**Comment by aserawayneasera** [comment]
thanks Morten. 
I hope it is okay if I use the image address as https://lipis.github.io/flag-icon-css/flags/4x3/gb.svg instead of saving it on the github.

**Comment by MortenHofft** [comment]
It is probably fine, but I would suggest copying them to your own repository. That website could in theory disappear tomorrow.
